[toolchain]
package_manager = "pnpm"
anchor_version = "0.31.1"
solana_version = "2.2.11"

[features]
resolution = true
skip-lint = false

[programs.devnet]
tributary = "TRibg8W8zmPHQqWtyAD1rEBRXEdyU13Mu6qX1Sg42tJ"

[programs.mainnet]
tributary = "TRibg8W8zmPHQqWtyAD1rEBRXEdyU13Mu6qX1Sg42tJ"

[programs.localnet]
tributary = "TRibg8W8zmPHQqWtyAD1rEBRXEdyU13Mu6qX1Sg42tJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor run test-cargo && anchor run test-integration && anchor run test-composable"
test-cargo = "cargo test"
test-integration = "npx jest ./tests/tributary.test.ts --preset ts-jest"
test-composable = "npx jest ./tests/composable.test.ts --preset ts-jest"

# Surfpool tests
test-surfpool = "npx jest ./tests/surfpool.test.ts --preset ts-jest"
test-topup = "npx jest ./tests/topup-balance.test.ts --preset ts-jest"
test-topup-swap = "npx jest ./tests/topup-balance-swap.test.ts --preset ts-jest"
test-topup-sol = "npx jest ./tests/topup-balance-sol.test.ts --preset ts-jest"

[test]
startup_wait = 20000

# This deploys the program using --upgradeable-program, and the initial upgrade authority will be set to provider.wallet
upgradeable = true
