[toolchain]
package_manager = "pnpm"
anchor_version = "0.31.1"
solana_version = "2.2.11"

[features]
resolution = true
skip-lint = false

[programs.localnet]
recurring_payments = "CPt2GNFqP5ZAaF1mGYseAi7eRi9aNavqb9sByF5Ypayi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec jest --preset ts-jest"

[test]
startup_wait = 20000
