[toolchain]
package_manager = "pnpm"
anchor_version = "0.31.1"
solana_version = "2.2.11"

[features]
resolution = true
skip-lint = false

[programs.devnet]
tributary = "TRibg8W8zmPHQqWtyAD1rEBRXEdyU13Mu6qX1Sg42tJ"

[programs.mainnet]
tributary = "TRibg8W8zmPHQqWtyAD1rEBRXEdyU13Mu6qX1Sg42tJ"

[programs.localnet]
tributary = "TRibg8W8zmPHQqWtyAD1rEBRXEdyU13Mu6qX1Sg42tJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test && pnpm exec jest ./tests --preset ts-jest"

[test]
startup_wait = 20000
