// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:8989827404cac89c
use anchor_lang::prelude::*;

#[error_code]
pub enum TributaryError {
    ProgramPaused = 0,
    InvalidAmount = 1,
    Unauthorized = 2,
    PaymentNotDue = 3,
    PolicyExpired = 4,
    ArithmeticOverflow = 5,
    InsufficientDelegatedAmount = 6,
    PolicyPaused = 7,
    CombinedFeeBpsExceedsMax = 8,
    InvalidLifecycle = 9,
}
// ---- END GENERATED ----
