// ---- GENERATED BY QEDGEN — DO NOT EDIT — regenerated from .qedspec ----
//! Per-handler guard checks derived from the `.qedspec`.
//! Called from user-owned `instructions/<name>::handler` before
//! business logic; keep guard logic here, policy-free logic there.

#![allow(unused_variables, unused_imports, dead_code, clippy::too_many_arguments)]

use anchor_lang::prelude::*;
use crate::errors::*;
use crate::state::*;
use crate::ref_impls::*;
use crate::*;

/// Guards for `create_payment_policy`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn create_payment_policy<'info>(ctx: &mut CreatePaymentPolicy<'info>, max_per_period: u64, max_chunk: u64, period_secs: u64, fee_bps: u16, proto_share: u16, sched_share: u16, referral_share: u16) -> Result<()> {
    // requires: max_per_period > 0
    if !(max_per_period > 0) { return Err(TributaryError::InvalidAmount.into()); }
    // requires: max_chunk > 0
    if !(max_chunk > 0) { return Err(TributaryError::InvalidAmount.into()); }
    // requires: max_chunk ≤ max_per_period
    if !(max_chunk <= max_per_period) { return Err(TributaryError::InvalidAmount.into()); }
    // requires: period_secs > 0
    if !(period_secs > 0) { return Err(TributaryError::InvalidAmount.into()); }
    // requires: (proto_share + sched_share + referral_share) ≤ 10000
    if !((proto_share + sched_share + referral_share) <= 10000) { return Err(TributaryError::CombinedFeeBpsExceedsMax.into()); }
    Ok(())
}

/// Guards for `execute_payment_case_0`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn execute_payment_case_0<'info>(ctx: &mut ExecutePaymentCase0<'info>, chunk: u64, current_time: u64) -> Result<()> {
    // requires: emergency_pause = 0
    if !(emergency_pause == 0) { return Err(TributaryError::ProgramPaused.into()); }
    // requires: policy_status = 0
    if !(policy_status == 0) { return Err(TributaryError::PolicyPaused.into()); }
    // requires: chunk > 0
    if !(chunk > 0) { return Err(TributaryError::InvalidAmount.into()); }
    // requires: chunk ≤ max_chunk_amount
    if !(chunk <= max_chunk_amount) { return Err(TributaryError::InvalidAmount.into()); }
    // requires: is_net_mode = 0
    if !(is_net_mode == 0) { return Err(anchor_lang::error::Error::from(ProgramError::Custom(0xFF))); }
    // requires: current_time ≥ current_period_start + period_length_seconds ∧ chunk ≤ max_amount_per_period
    if !((current_time >= current_period_start + period_length_seconds) && (chunk <= max_amount_per_period)) { return Err(anchor_lang::error::Error::from(ProgramError::Custom(0xFF))); }
    Ok(())
}

/// Guards for `execute_payment_case_1`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn execute_payment_case_1<'info>(ctx: &mut ExecutePaymentCase1<'info>, chunk: u64, current_time: u64) -> Result<()> {
    // requires: emergency_pause = 0
    if !(emergency_pause == 0) { return Err(TributaryError::ProgramPaused.into()); }
    // requires: policy_status = 0
    if !(policy_status == 0) { return Err(TributaryError::PolicyPaused.into()); }
    // requires: chunk > 0
    if !(chunk > 0) { return Err(TributaryError::InvalidAmount.into()); }
    // requires: chunk ≤ max_chunk_amount
    if !(chunk <= max_chunk_amount) { return Err(TributaryError::InvalidAmount.into()); }
    // requires: is_net_mode = 0
    if !(is_net_mode == 0) { return Err(anchor_lang::error::Error::from(ProgramError::Custom(0xFF))); }
    // requires: ¬(current_time ≥ current_period_start + period_length_seconds ∧ chunk ≤ max_amount_per_period)
    if !(!((current_time >= current_period_start + period_length_seconds) && (chunk <= max_amount_per_period))) { return Err(anchor_lang::error::Error::from(ProgramError::Custom(0xFF))); }
    // requires: current_time < current_period_start + period_length_seconds ∧ chunk ≤ max_amount_per_period - current_period_total
    if !((current_time < current_period_start + period_length_seconds) && (chunk <= max_amount_per_period - current_period_total)) { return Err(anchor_lang::error::Error::from(ProgramError::Custom(0xFF))); }
    Ok(())
}

/// Guards for `execute_payment_otherwise`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn execute_payment_otherwise(ctx: &ExecutePaymentOtherwise, chunk: u64, current_time: u64) -> Result<()> {
    // requires: emergency_pause = 0
    if !(emergency_pause == 0) { return Err(TributaryError::ProgramPaused.into()); }
    // requires: policy_status = 0
    if !(policy_status == 0) { return Err(TributaryError::PolicyPaused.into()); }
    // requires: chunk > 0
    if !(chunk > 0) { return Err(TributaryError::InvalidAmount.into()); }
    // requires: chunk ≤ max_chunk_amount
    if !(chunk <= max_chunk_amount) { return Err(TributaryError::InvalidAmount.into()); }
    // requires: is_net_mode = 0
    if !(is_net_mode == 0) { return Err(anchor_lang::error::Error::from(ProgramError::Custom(0xFF))); }
    // requires: ¬(current_time ≥ current_period_start + period_length_seconds ∧ chunk ≤ max_amount_per_period)
    if !(!((current_time >= current_period_start + period_length_seconds) && (chunk <= max_amount_per_period))) { return Err(anchor_lang::error::Error::from(ProgramError::Custom(0xFF))); }
    // requires: ¬(current_time < current_period_start + period_length_seconds ∧ chunk ≤ max_amount_per_period - current_period_total)
    if !(!((current_time < current_period_start + period_length_seconds) && (chunk <= max_amount_per_period - current_period_total))) { return Err(anchor_lang::error::Error::from(ProgramError::Custom(0xFF))); }
    // requires: 0 = 1
    if !(false) { return Err(TributaryError::InsufficientDelegatedAmount.into()); }
    Ok(())
}

/// Guards for `execute_composable_case_0`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn execute_composable_case_0<'info>(ctx: &mut ExecuteComposableCase0<'info>, chunk: u64, current_time: u64, min_output: u64) -> Result<()> {
    // requires: emergency_pause = 0
    if !(emergency_pause == 0) { return Err(TributaryError::ProgramPaused.into()); }
    // requires: policy_status = 0
    if !(policy_status == 0) { return Err(TributaryError::PolicyPaused.into()); }
    // requires: chunk > 0
    if !(chunk > 0) { return Err(TributaryError::InvalidAmount.into()); }
    // requires: chunk ≤ max_chunk_amount
    if !(chunk <= max_chunk_amount) { return Err(TributaryError::InvalidAmount.into()); }
    // requires: is_net_mode = 0
    if !(is_net_mode == 0) { return Err(anchor_lang::error::Error::from(ProgramError::Custom(0xFF))); }
    // requires: current_time ≥ current_period_start + period_length_seconds ∧ chunk ≤ max_amount_per_period
    if !((current_time >= current_period_start + period_length_seconds) && (chunk <= max_amount_per_period)) { return Err(anchor_lang::error::Error::from(ProgramError::Custom(0xFF))); }
    Ok(())
}

/// Guards for `execute_composable_case_1`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn execute_composable_case_1<'info>(ctx: &mut ExecuteComposableCase1<'info>, chunk: u64, current_time: u64, min_output: u64) -> Result<()> {
    // requires: emergency_pause = 0
    if !(emergency_pause == 0) { return Err(TributaryError::ProgramPaused.into()); }
    // requires: policy_status = 0
    if !(policy_status == 0) { return Err(TributaryError::PolicyPaused.into()); }
    // requires: chunk > 0
    if !(chunk > 0) { return Err(TributaryError::InvalidAmount.into()); }
    // requires: chunk ≤ max_chunk_amount
    if !(chunk <= max_chunk_amount) { return Err(TributaryError::InvalidAmount.into()); }
    // requires: is_net_mode = 0
    if !(is_net_mode == 0) { return Err(anchor_lang::error::Error::from(ProgramError::Custom(0xFF))); }
    // requires: ¬(current_time ≥ current_period_start + period_length_seconds ∧ chunk ≤ max_amount_per_period)
    if !(!((current_time >= current_period_start + period_length_seconds) && (chunk <= max_amount_per_period))) { return Err(anchor_lang::error::Error::from(ProgramError::Custom(0xFF))); }
    // requires: current_time < current_period_start + period_length_seconds ∧ chunk ≤ max_amount_per_period - current_period_total
    if !((current_time < current_period_start + period_length_seconds) && (chunk <= max_amount_per_period - current_period_total)) { return Err(anchor_lang::error::Error::from(ProgramError::Custom(0xFF))); }
    Ok(())
}

/// Guards for `execute_composable_otherwise`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn execute_composable_otherwise(ctx: &ExecuteComposableOtherwise, chunk: u64, current_time: u64, min_output: u64) -> Result<()> {
    // requires: emergency_pause = 0
    if !(emergency_pause == 0) { return Err(TributaryError::ProgramPaused.into()); }
    // requires: policy_status = 0
    if !(policy_status == 0) { return Err(TributaryError::PolicyPaused.into()); }
    // requires: chunk > 0
    if !(chunk > 0) { return Err(TributaryError::InvalidAmount.into()); }
    // requires: chunk ≤ max_chunk_amount
    if !(chunk <= max_chunk_amount) { return Err(TributaryError::InvalidAmount.into()); }
    // requires: is_net_mode = 0
    if !(is_net_mode == 0) { return Err(anchor_lang::error::Error::from(ProgramError::Custom(0xFF))); }
    // requires: ¬(current_time ≥ current_period_start + period_length_seconds ∧ chunk ≤ max_amount_per_period)
    if !(!((current_time >= current_period_start + period_length_seconds) && (chunk <= max_amount_per_period))) { return Err(anchor_lang::error::Error::from(ProgramError::Custom(0xFF))); }
    // requires: ¬(current_time < current_period_start + period_length_seconds ∧ chunk ≤ max_amount_per_period - current_period_total)
    if !(!((current_time < current_period_start + period_length_seconds) && (chunk <= max_amount_per_period - current_period_total))) { return Err(anchor_lang::error::Error::from(ProgramError::Custom(0xFF))); }
    // requires: 0 = 1
    if !(false) { return Err(TributaryError::InsufficientDelegatedAmount.into()); }
    Ok(())
}

/// Guards for `transfer`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn transfer<'info>(ctx: &mut Transfer<'info>, amount: u64) -> Result<()> {
    // requires: emergency_pause = 0
    if !(emergency_pause == 0) { return Err(TributaryError::ProgramPaused.into()); }
    // requires: policy_status = 0
    if !(policy_status == 0) { return Err(TributaryError::PolicyPaused.into()); }
    // requires: amount > 0
    if !(amount > 0) { return Err(TributaryError::InvalidAmount.into()); }
    Ok(())
}

/// Guards for `release_milestone`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn release_milestone<'info>(ctx: &mut ReleaseMilestone<'info>, current_time: u64, due_timestamp: u64) -> Result<()> {
    // requires: emergency_pause = 0
    if !(emergency_pause == 0) { return Err(TributaryError::ProgramPaused.into()); }
    // requires: policy_status = 0
    if !(policy_status == 0) { return Err(TributaryError::PolicyPaused.into()); }
    // requires: release_due_date = 0 ∨ current_time ≥ due_timestamp
    if !((release_due_date == 0) || (current_time >= due_timestamp)) { return Err(TributaryError::PaymentNotDue.into()); }
    // requires: release_requires_gateway = 0 ∨ caller_is_gateway = 1
    if !((release_requires_gateway == 0) || (caller_is_gateway == 1)) { return Err(TributaryError::Unauthorized.into()); }
    // requires: release_requires_owner = 0 ∨ caller_is_owner = 1
    if !((release_requires_owner == 0) || (caller_is_owner == 1)) { return Err(TributaryError::Unauthorized.into()); }
    // requires: release_requires_recipient = 0 ∨ caller_is_recipient = 1
    if !((release_requires_recipient == 0) || (caller_is_recipient == 1)) { return Err(TributaryError::Unauthorized.into()); }
    // requires: is_net_mode = 0
    if !(is_net_mode == 0) { return Err(anchor_lang::error::Error::from(ProgramError::Custom(0xFF))); }
    Ok(())
}

// ---- END GENERATED ----
