// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:b023ae3135d88af4
#![allow(unexpected_cfgs)]

use anchor_lang::prelude::*;

mod instructions;
pub mod errors;
pub mod state;
pub mod guards;
pub mod ref_impls;

declare_id!("TRibg8W8zmPHQqWtyAD1rEBRXEdyU13Mu6qX1Sg42tJ");

#[program]
pub mod tributary {
    use super::*;

    pub fn create_payment_policy(ctx: Context<CreatePaymentPolicy>, max_per_period: u64, max_chunk: u64, period_secs: u64, fee_bps: u16, proto_share: u16, sched_share: u16, referral_share: u16) -> Result<()> {
        ctx.accounts.handler(max_per_period, max_chunk, period_secs, fee_bps, proto_share, sched_share, referral_share)
    }

    pub fn execute_payment_case_0(ctx: Context<ExecutePaymentCase0>, chunk: u64, current_time: u64) -> Result<()> {
        ctx.accounts.handler(chunk, current_time)
    }

    pub fn execute_payment_case_1(ctx: Context<ExecutePaymentCase1>, chunk: u64, current_time: u64) -> Result<()> {
        ctx.accounts.handler(chunk, current_time)
    }

    pub fn execute_payment_otherwise(ctx: Context<ExecutePaymentOtherwise>, chunk: u64, current_time: u64) -> Result<()> {
        ctx.accounts.handler(chunk, current_time)
    }

    pub fn execute_composable_case_0(ctx: Context<ExecuteComposableCase0>, chunk: u64, current_time: u64, min_output: u64) -> Result<()> {
        ctx.accounts.handler(chunk, current_time, min_output)
    }

    pub fn execute_composable_case_1(ctx: Context<ExecuteComposableCase1>, chunk: u64, current_time: u64, min_output: u64) -> Result<()> {
        ctx.accounts.handler(chunk, current_time, min_output)
    }

    pub fn execute_composable_otherwise(ctx: Context<ExecuteComposableOtherwise>, chunk: u64, current_time: u64, min_output: u64) -> Result<()> {
        ctx.accounts.handler(chunk, current_time, min_output)
    }

    pub fn transfer(ctx: Context<Transfer>, amount: u64) -> Result<()> {
        ctx.accounts.handler(amount)
    }

    pub fn release_milestone(ctx: Context<ReleaseMilestone>, current_time: u64, due_timestamp: u64) -> Result<()> {
        ctx.accounts.handler(current_time, due_timestamp)
    }

}

// `#[derive(Accounts)]` structs live at the crate root so the
// Anchor `#[program]` macro can resolve them via `crate::*`.
// The handler impl blocks live next to the (always-regenerated)
// guard module in `instructions/<name>.rs`.
use crate::state::*;

#[derive(Accounts)]
pub struct CreatePaymentPolicy<'info> {
    #[account(mut)]
    pub state: Account<'info, TributaryAccount>,
}

#[derive(Accounts)]
pub struct ExecutePaymentCase0<'info> {
    #[account(mut)]
    pub state: Account<'info, TributaryAccount>,
}

#[derive(Accounts)]
pub struct ExecutePaymentCase1<'info> {
    #[account(mut)]
    pub state: Account<'info, TributaryAccount>,
}

#[derive(Accounts)]
pub struct ExecutePaymentOtherwise {
}

#[derive(Accounts)]
pub struct ExecuteComposableCase0<'info> {
    #[account(mut)]
    pub state: Account<'info, TributaryAccount>,
}

#[derive(Accounts)]
pub struct ExecuteComposableCase1<'info> {
    #[account(mut)]
    pub state: Account<'info, TributaryAccount>,
}

#[derive(Accounts)]
pub struct ExecuteComposableOtherwise {
}

#[derive(Accounts)]
pub struct Transfer<'info> {
    #[account(mut)]
    pub state: Account<'info, TributaryAccount>,
}

#[derive(Accounts)]
pub struct ReleaseMilestone<'info> {
    #[account(mut)]
    pub state: Account<'info, TributaryAccount>,
}
// ---- END GENERATED ----
