// ---- GENERATED BY QEDGEN — DO NOT EDIT ----
//! Reference implementations (from qedspec `ref_impl` declarations).
//! Pure expressions — no state mutation, no side effects.
//! Generated alongside guards.rs so `requires` / `ensures` clauses
//! and user handler bodies can call them by name.

#![allow(dead_code, clippy::too_many_arguments)]

#[inline]
pub fn bps_mul(amount: u64, bps: u16) -> u64 {
    mul_div_floor_u128(((amount) as u128), ((bps) as u128), ((10000) as u128))
}

// ---- END GENERATED ----
