/**
 * Central OpenAPI specification
 *
 * Generated by swagger-jsdoc from the JSDoc `@openapi` annotations on the
 * Express routers in `./src/routes/*.ts`. Mounted in `./src/index.ts` and
 * served at `/openapi.json`, `/openapi.yaml`, and `/docs` (Swagger UI).
 *
 * The checked-in `apps/api/openapi.yaml` is the static baseline that the
 * mkdocs documentation build copies — regenerate it after route changes by
 * hitting the live `/openapi.yaml` endpoint.
 */

import swaggerJsdoc from "swagger-jsdoc";

const options: swaggerJsdoc.Options = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "Tributary API",
      version: "1.9.0",
      description:
        "Modular Express API for subscription and payment services on Solana. " +
        "Provides health checks, subscription status lookups, on-chain event " +
        "queries, webhook management, JWT issuance, JWKS publishing, and " +
        "admin key rotation.",
      license: {
        name: "MIT",
      },
    },
    servers: [
      { url: "https://api.tributary.so", description: "Production" },
      { url: "http://localhost:3002", description: "Local development" },
    ],
    components: {
      securitySchemes: {
        AdminApiKey: {
          type: "apiKey",
          in: "header",
          name: "x-admin-key",
          description: "Admin API key (ADMIN_API_KEY env var on the server).",
        },
      },
      schemas: {
        Error: {
          type: "object",
          required: ["error"],
          properties: {
            success: { type: "boolean", example: false },
            error: { type: "string" },
            timestamp: {
              type: "integer",
              description: "Unix epoch milliseconds.",
            },
          },
        },
        Webhook: {
          type: "object",
          required: ["id", "gateway_pubkey", "endpoint_url", "active"],
          properties: {
            id: { type: "integer", example: 1 },
            gateway_pubkey: {
              type: "string",
              minLength: 32,
              maxLength: 44,
              description: "Gateway authority public key.",
            },
            endpoint_url: {
              type: "string",
              format: "uri",
              description: "Webhook target URL.",
            },
            active: { type: "boolean", example: true },
            created_at: {
              type: "string",
              format: "date-time",
            },
            updated_at: {
              type: "string",
              format: "date-time",
            },
          },
        },
      },
    },
    tags: [
      { name: "Health", description: "Service health probes" },
      { name: "Skill", description: "Lando skill markdown generation" },
      { name: "Subscriptions", description: "Recurring subscription lookups" },
      { name: "OneTime", description: "One-time payment lookups" },
      { name: "Events", description: "On-chain event queries" },
      { name: "Webhooks", description: "Webhook endpoint management" },
      {
        name: "Tokens",
        description:
          "JWT issuance for active payment policies (all 5 PolicyType variants) and direct payments",
      },
      { name: "JWKS", description: "JWT key set publishing" },
      { name: "Admin", description: "Administrative key rotation" },
    ],
  },
  apis: ["./src/routes/*.ts"],
};

export const openapiSpec = swaggerJsdoc(options);
