name: Anchor Tests

on:
  push:
    branches: [main]
    paths:
      - "programs/**"
      - "tests/**"
      - "Anchor.toml"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/*program*"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Build SDK
        working-directory: ./sdk
        run: pnpm run build

      - uses: solana-developers/github-actions/extract-versions@v0.2.5
        id: versions

      - uses: solana-developers/github-actions/setup-all@v0.2.5
        with:
          solana_version: ${{ steps.versions.outputs.solana_version }}
          anchor_version: ${{ steps.versions.outputs.anchor_version }}
          node_version: 22

      - uses: solana-developers/github-actions/run-tests@v0.2.5
        with:
          solana_version: ${{ steps.versions.outputs.solana_version }}
          anchor_version: ${{ steps.versions.outputs.anchor_version }}
          program: tributary
