name: Test Package

on:
  workflow_call:
    inputs:
      path:
        type: string
        required: true
      name:
        type: string
        required: false
        default: ""

env:
  NODE_VERSION: "22"
  PNPM_VERSION: "9.6.0"

jobs:
  test:
    name: Test ${{ inputs.name || inputs.path }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ inputs.path }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linter
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test
